### ISSUE TITLE
User can generate random dog picture

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/ajax-project#1]
## 💰 Motivation
Brighten up user's day with cute dog picture.

## 📐 Plan

When the user clicks a button labeled "Tailwags" a random dog picture is generated from dogs API and displayed on the page. 

## 🖼️ Wireframe

![Screen Shot 2021-02-26 at 10 25 14 AM](https://user-images.githubusercontent.com/74885918/109350212-fbe5cb80-782b-11eb-814c-1a6404a9935e.png)

## ✅ Task List

- [x] Create a header
- [x] Create a container that will hold content 
- [x] Make navigation buttons
- [x] Make div with class tailwags (display hidden) 
- [x] Match styling to wireframe
- [x] Ensure that the app looks nice on both mobile-sized and desktop-sized screens.
- [x] Listen for `click` events on navigation buttons 
- [x] when navigation button is clicked, homepage should be hidden 
- [x] Verify that every time that tailwags is clicked, new dog image appears
- [x] Create array for greetings and names
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality in private browsing and fix any errors.
