### ISSUE TITLE
User can generate random inspirational quote

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/ajax-project#2]
## 💰 Motivation
Brighten up user's day with an inspirational quote.

## 📐 Plan
When the user clicks on button labeled "Stay Pawsitive" a random inpirational quote is generated from quotable API and displayed on the page.

## 🖼️ Wireframe
![Screen Shot 2021-02-26 at 10 25 36 AM](https://user-images.githubusercontent.com/74885918/109350332-2df72d80-782c-11eb-9781-23125659374e.png)

## ✅ Task List

- [x] Create a container div 
- [x] Format content to match wireframe
- [x] Ensure that app looks nice on both mobile-sized and desktop-sized screens
- [x] Add conditional to event handler function to check event target
- [x] Make XMLHttp request to API
- [x] Verify that new quote is generated when button stay pawsitive is clicked 
- [x] Listen for 'click' events on menu icon 
- [x] Remove unnecessary styling
- [x] Test functionality in private browsing and fix any errors
