### ISSUE TITLE
User can add entry

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/ajax-project#3]
## 💰 Motivation
User can reflect on their day by adding an entry.

## 📐 Plan
User is able to save favortites when clicking on an icon.

## 🖼️ Wireframe
![Screen Shot 2021-02-26 at 10 45 33 AM](https://user-images.githubusercontent.com/74885918/109341817-c89d3f80-781f-11eb-844d-f1f311af44ea.png)

## ✅ Task List

- [x]  Create a div container for section
- [x] Add a form and text area for user to record thoughts
- [x] Listen for 'submit' event on the form 
- [x]  Put the form's input values into a new object.
- [x] Add the nextEntryId to the object.
- [x] Increment the nextEntryId on the data model.
- [x] Prepend the new object to the entries in the data model.
- [x] Reset the form inputs.
- [x] Verify that new entries are saved to local storage
- [x] Verify that each new entry receives an incrementing entryId.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
