### ISSUE TITLE
User can view entry

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/ajax-project#4]
## 💰 Motivation
User can view entries.

## 📐 Plan
Display user's entries in order from most recent to least recent. 

## 🖼️ Wireframe
![Screen Shot 2021-02-26 at 1 19 49 PM](https://user-images.githubusercontent.com/74885918/109356265-533c6980-7835-11eb-83fe-ce5ddc08664c.png)

## ✅ Task List

- [x] Add a button to homepage labeled Entries
- [x]  Add container div for entries section
- [x] Add an unordered list with some dummy entries
- [x] Verify that entries look good on mobile and desktop
- [x] Define a function that takes a single entry object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each entry in the data model and append it to the page when the 'DOMContentLoaded' event is fired.
- [x] Remove example HTML entries once the user's entries are successfully being appended to the DOM on the page load.
- [x] Ensure that submitting a new entry also creates a new DOM tree for it and takes user to entries section.
- [x] Test app functionality in a private browsing tab.
- [x] Remove unnecessary styling and fix any remaining errors.
