### ISSUE TITLE
User can delete entry

### ISSUE THREAD

**Issue by yesseniarod** [yesseniarod/ajax-project#5]
## 💰 Motivation
User can remove entry from list that they no longer wish to save. 

## 📐 Plan
Allow user to modify entries list by deleting content they no longer want to save.

## 🖼️ Wireframe
![Screen Shot 2021-03-02 at 8 45 41 PM](https://user-images.githubusercontent.com/74885918/109754171-697d5900-7b98-11eb-9b2e-1fdea815c3f9.png)

## ✅ Task List

- [x] Add a delete anchor next to individual entries
- [x] Create a modal 
- [x] Listen for click event on delete anchor, modal should open when icon is clicked
- [x] User response should close modal
- [x] Remove entry from data model
- [x] Remove unnecessary styling
- [x] Fix all errors
